first
OlegYankiwskyi/TableView pull request #1
Opened 2018-04-12 13:10 UTC by OlegYankiwskyi

2018-04-13 11:55 UTC, AlexeyTyurenkov requested changes

2018-04-13 11:55 UTC, AlexeyTyurenkov commented on TableView/CustomCell.swift
> +class CustomCell: UITableViewCell {
Let it be DataStructureTableCell

2018-04-13 11:55 UTC, AlexeyTyurenkov commented on TableView/Protocol/StructDataModelProtocol.swift
> +    func getData() -> [String]
why do we need it?

2018-04-13 11:55 UTC, AlexeyTyurenkov commented on TableView/ViewController.swift
> +class ViewController: UIViewController {
Could you rename it into more selfdescribing name?

2018-04-13 11:55 UTC, AlexeyTyurenkov commented on TableView/ViewController.swift
> +        self.tableView(tableView, didDeselectRowAt: indexPath)
it's better to use tableview from the method parameters

2018-04-13 11:55 UTC, AlexeyTyurenkov commented on TableView/ViewController.swift
> +            return tableView.dequeueReusableCell(withIdentifier: CustomCell.identifier, for: indexPath)
what do this code do?

2018-04-13 11:56 UTC, AlexeyTyurenkov commented
---

2018-04-13 11:57 UTC, AlexeyTyurenkov requested changes
Fix it

2018-04-16 11:46 UTC, OlegYankiwskyi commented on TableView/Model/ConfigureCellModel.swift
> +    }
I don't think that I understand first task.

2018-04-19 09:55 UTC, AlexeyTyurenkov requested changes

2018-04-19 09:55 UTC, AlexeyTyurenkov commented on TableView/Controllers/DetailController.swift
> +        if buttonShowText.currentTitle! == "More" {
What should be done in case we will use another word there?

2018-04-19 09:55 UTC, AlexeyTyurenkov commented on TableView/Models/ConfigureCellModel.swift
> +        model.label.text = value
cell isn't model itself
Cell is always view
I'm not sure if we need separate class for this particular case

2018-04-19 09:55 UTC, AlexeyTyurenkov commented on TableView/Protocols/ArrayDataProtocol.swift
> +    func getElement(at: Int) -> DataStructureModel
better naming 
func at(index: Int)-> ...EntityProtocol

2018-04-19 09:55 UTC, AlexeyTyurenkov commented on TableView/Models/ArrayDataModel.swift
> +    func getElement(at: Int) -> DataStructureModel {
I guess it should return DataStructureModelProtocol

2018-04-23 14:41 UTC, AlexeyTyurenkov approved these changes

2018-04-23 14:41 UTC, AlexeyTyurenkov commented on TableView/Controllers/DetailController.swift
> +        self.setTitle(title, for: .focused)
did you mean .highlighted here

2018-04-23 14:44 UTC, merged